config/routes.rb
Rails.application.routes.draw do
  mount Blazer::Engine, at: "blazer"

  resources :orders
 devise_for :users
 
  devise_for :models
  resources :listings do
	resources :orders, only: [:new ,:create]
	devise_for :users
resources :users, :only => [:show]
    end
    mount Commontator::Engine => '/commontator'
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get  '/listings/:id/graphs', to:  'listings#graphs' , as: 'listinggraphs'
get '/users/:id' ,to: 'users#show',as: 'usershow'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
 mount_uploaders :images, ImageUploader
   serialize :images, JSON # If you use SQLite, add this line.
 mount_uploader :video, VideoUploader  
 validates :name,:description,:price, presence: true 
   visitable :ahoy_visit
 validates :price, numericality: {greater_than: 0}
 belongs_to :user
 has_many :orders
 has_many :visits , class_name: 'Ahoy::Visit'
 acts_as_commontable
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:edit,:new ,:create ,:destroy,:update]
  before_action :check_user, only: [:edit,:update,:destroy]
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end
  def check_user
		if current_user != @listing.user
		redirect_to root_url,alert: "Sorry,this listing belongs to someone else"
	end
	end
  # GET /listings/1
  # GET /listings/1.json
  def show
        @listing = Listing.find(params[:id])

ahoy.track "controller", listingid: @listing.id

  end
  
  def seller
	    @listings = Listing.where(user: current_user)

	end
    
  def graphs
                  @listing = Listing.find(params[:id])
	                  @new = @listing.id   	    

	  
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
	@listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save 
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price , {images: []},:video)
    end
	
	
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing,:html==>{multipart: true}, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
	

	<h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter the Item Name" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control",placeholder:"Enter Description"  %>
  </div>

  <div class="form-group">
    <%= form.label :price %>**in $**
    <%= form.text_field :price, class:"form-control",placeholder:"Enter the Price"  %>
  </div>

    
	<div class="form-group">
    <%= form.label :images %>**add 3/6/9 images Only**
    <%= form.file_field :images, multiple: true, class:"form-control"%>
  </div>

<div class="form-group">
    <%= form.label :video %>
    <%= form.file_field :video , class:"form-control"%>
  </div>


  <div class="form-group">
    <%= form.submit  class:"btn btn-success" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing , class:'btn btn-link'%> |
<%= link_to 'Back', listings_path, class:'btn btn-link' %>

app/views/listings/graphs.html.erb
<style>
h1{
font-family: "Times New Roman", Times, serif;
}
</style>

<h1>no of views</h1>

<%= line_chart Ahoy::Event.where_event("controller", "listingid":@listing.id).group_by_day(:time).count %>
    group by months
    <%= line_chart Ahoy::Event.where_event("controller", "listingid":@listing.id).group_by_month(:time).count %>


<h1>no of ORDERS<h1>
<%= line_chart Ahoy::Event.where_event("buynow", "listingid":@listing.id).group_by_day(:time).count %>

 
	
			<center><button><h1><%= link_to "Sales History", sales_path %></h1></button></center>

app/views/listings/index.html.erb
<style>
h2{
font-family: "Times New Roman", Times, serif;
}
</style>
<script src="timeme.js"></script>
<script type="text/javascript">
	TimeMe.initialize({
		currentPageName: "my-home-page", // current page
		idleTimeoutInSeconds: 30 // seconds
	});		
</script>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1" ></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="4.jpg" alt="Chania">
      <div class="carousel-caption">
        <h3>Los Angeles</h3>
        <p>LA is always so much fun!</p>
      </div>
    </div>

    <div class="item">
      <img src="1.jpg" alt="Chicago">
      <div class="carousel-caption">
        <h3>Chicago</h3>
        <p>Thank you, Chicago!</p>
      </div>
    </div>

    <div class="item">
      <img src="3.jpg" alt="New York">
      <div class="carousel-caption">
        <h3>New York</h3>
        <p>We love the Big Apple!</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>





<h2><b>Listings</b></h2>
<div class="row">

<% @listings.each do |listing| %>
	<div class="col-md-4 ">
	

	<td><%= image_tag listing.images_urls(:thumb)[1].to_s%></td>
	<div class="caption">
		<td><%= listing.name %></td><br>
        
		<td><%= listing.price %>$/-</td>
		<td><%= "Sold by #{listing.user.name}" %></td>

		
		<td><%= link_to 'Show', listing, class:'btn btn-link' %></td>
		<% if (user_signed_in?) && (current_user == listing.user) %>
		
   
      </tr>
	  <% end %>
	  
		</div>
	</div>
<% end %>

</div>


<% if(user_signed_in?) %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<style>
h1{
font-family: "Times New Roman", Times, serif;
}
</style>

<h1>Listings</h1>
<table class="table table-striped table-bordered">
<tr>
	<th class="center">Name</th>
	<th class="center">Description</th>
	<th class="center">price</th>
	<th class="center">Action</th>
</tr>
<% @listings.each do |listing| %>
	<tr>
		<td><%= listing.name %></td><br>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td>
				<li><%= link_to 'Analytics', listinggraphs_path(listing) , class:'btn btn-link' %></li>
				<li><%= link_to 'Edit', edit_listing_path(listing) , class:'btn btn-link' %></li>
				<li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-link' %>
				</li>
				</ul></button>
			</div></td>
	</tr>
	<% end %>
    
</table>  
			<center><button><h1><%= link_to "Sales History", sales_path %></h1></button></center>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>


<script type="text/javascript">
onload=function(){
var mydiv=document.getElementById('video1');
if(!mydiv.hasChildNodes()){mydiv.style.display='none'}
}
document.addEventListener("DOMContentLoaded", function() {
    console.log("DOM fully loaded and parsed");
    document.querySelector("#listing").addEventListener("DOMContentLoaded", function(e) {
    
    ahoy.track("Viewed listing", e.target.dataset);
    });
    });
    ahoy.trackAll();
    </script>
    <link href='https://fonts.googleapis.com/css?family=Alex Brush' rel='stylesheet'>
    <style>
h1{
font-family: 'Lato';font-size: 32px;
}
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  cursor: pointer;
  border-radius: 8px;
}
.button5 {
  background-color: white;
  color: black;
  border: 2px solid #4CAF50;
}


.button5:hover {
  background-color: #4CAF50;
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  color: white;
}

.button2 {
  background-color: white;
  color: black;
  border: 2px solid #008CBA;
  width: 50%;
}


.button2:hover {
  background-color: #008CBA;
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  color: white;
}

</style>
 <div class="form-group"><p>
  <h1> <strong><%= @listing.name %></strong></h1>
</p>

 <% @listing.images_urls.each do |url| %>
	<div class="col-md-4" class="img-responsive" alt="Responsive image">
     <%= image_tag url ,:size => "260x180" %>
	</div>
<% end %>
	
<div class="video1"><%=video_tag @listing.video_url.to_s, :controls =>true if @listing.video?%></div> 
	
   
<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>$ ONLY/-
</p>
<div id="listing",data:{id: <%=@listing.id%> }></div>
<center>	<%= link_to "BUY IT NOW", new_listing_order_path(@listing), class: "button button2"%> </center>|

</div>
<%= link_to "View Designers Profile", usershow_path(@listing.user),class:'button button5' %>
<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing) , class:'btn btn-link' %> |
<% end %>
<%= link_to 'Back', listings_path , class:'btn btn-link' %>

<%= commontator_thread(@listing) %>