config/routes.rb
Rails.application.routes.draw do
  mount Blazer::Engine, at: "blazer"

  resources :orders
 devise_for :users
 
  devise_for :models
  resources :listings do
	resources :orders, only: [:new ,:create]
	devise_for :users
resources :users, :only => [:show]
    end
    mount Commontator::Engine => '/commontator'
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get  '/listings/:id/graphs', to:  'listings#graphs' , as: 'listinggraphs'
get '/users/:id' ,to: 'users#show',as: 'usershow'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :name,:PinCode,:mobile,:size,:address, :city,  presence: true

  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
  
  def paypal_url(return_path)
    values = {
        business: "merchant@gotealeaf.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: listing.price,
        item_name: listing.name,
        item_number: listing.id,
        quantity: '1'
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

   
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
    
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user
   
  
	
  
  @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id
    @order.Email= current_user.email
    @order.selleremail= @seller.email
	
    respond_to do |format|
      if @order.save
                
      
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
		ahoy.track "buynow", listingid: @listing.id
         @buyeremail = User.new(params[:user])
        OrderRecievedMailer.sample_email(@order).deliver
        OrderRecievedMailer.seller(@order).deliver
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state, :name ,:mobile ,:PinCode , :size)
    end
	
	def total
		total=order.listing.price.sum
	end
	
	end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	*please refresh page if paypal button is not visible*
<div id="price" data-price="<%= @listing.price %>"></div>	
	
    
		<div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :size %>
    <%= form.text_field :size, class:"form-control" %>
  </div>

	<div class="form-group">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class:"form-control" %>
  </div>	
	
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:"form-control" %>
  </div>

<div class="form-group">
    <%= form.label :PinCode %>
    <%= form.text_field :PinCode, class:"form-control" %>
  </div>
<div class="form-group">
    <%= form.label :Landmark %>
    <%= form.text_field :Landmark, class:"form-control" %>
  </div>

  

  <div class="form-group">
    <%= form.label :Description %>(if any special changes)
    <%= form.text_field :Description, class:"form-control" %>
  </div>

 

    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"><div id="BUYNOW",data:{id: <%=@listing.id%> }> </div></div>
	
    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

    <script> 
    document.addEventListener("turbolinks:load",function(){
document.querySelector("#BUYNOW").addEventListener("click",function(e){
    ahoy.track("BUYNOW",e.target.dataset);
});
});
    
    
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
			
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: <%= @listing.price %>
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
					yourForm = document.getElementById('new_order');
                Rails.fire(yourForm, 'submit');
                
                });
            }
			
			
			
			

        }).render('#paypal-button-container');
		
		
    </script>

	
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', listing_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="center">
<h2>Your Purchase History </h2>
<table class="table table-striped table-bordered">
<tr>
	<th class="center">Item</th>
	<th class="center">Seller</th>
	<th class="center">Price</th>
	<th class="center">Date Purchased </th>
</tr>
<% @orders.each do |order| %>
	<tr>

		<td><%= order.listing.name %></td><br>
		<td><%= order.seller.name %></td>
        <td><%= order.listing.price %></td>		
		<td><%= order.created_at.strftime("%B %-d, %Y") %></td>
        
	</tr>
	<% end %>
	<tr>
			
	</tr>
</table>  
</div>

app/views/orders/sales.html.erb
<div class="center">
<h1>Your Sales History </h1>
<table class="table table-striped table-bordered">
<tr>
	<th class="center">Item</th>
	<th class="center">Customer</th>
    <th class="center">Size</th>
    <th class="center">state</th>
    <th class="center">city</th>
    <th class="center">address</th>
	<th class="center">mobile</th>
    <th class="center">Pincode</th>
    <th class="center">Date Sold</th>
</tr>

<% @orders.each do |order| %>
<div class="center">

	<tr>

		<td><%= order.listing.name %></td>
        <td><%= order.buyer.name %></td>
        
        <td><%= order.size %></td>
        <td><%= order.state %></td>
        <td><%= order.city %></td>
        <td><%= order.address %></td>
        <td><%= order.mobile %></td>
        <td><%= order.PinCode %></td>         
		<td><%= order.created_at.strftime("%B %-d, %Y") %></td>
        
	</tr>
	<% end %>
</table>  
		
		<% if(user_signed_in?) %>
<%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>