config/routes.rb
Rails.application.routes.draw do
  mount Blazer::Engine, at: "blazer"

  resources :orders
 devise_for :users
 
  devise_for :models
  resources :listings do
	resources :orders, only: [:new ,:create]
	devise_for :users
resources :users, :only => [:show]
    end
    mount Commontator::Engine => '/commontator'
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get  '/listings/:id/graphs', to:  'listings#graphs' , as: 'listinggraphs'
get '/users/:id' ,to: 'users#show',as: 'usershow'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
end

app/views/layouts/_footer.html.erb
<p>ONLY FOR THE BEST</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Roughma</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
		
      </ul>
      <ul class="nav navbar-nav navbar-right">
       
		<% if user_signed_in? %>
                    <li><%= link_to 'New Listing', new_listing_path %></li>

	 <li><%= link_to "View Profile", usershow_path(current_user) %></li>
		   <li><%= link_to "Your Cart", purchases_path %></li>
		 <li><%= link_to "Manage Listings", seller_path %></li>
		 <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
		<% else %>
		<li><a href="/users/sign_up">Sign Up</a></li>
		<li><a href="/users/sign_in">Sign in</a></li>
		
		<% end %>
		
		
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roughma</title>	
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

 <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

	
	
<%= render '/layouts/navbar' %>
  <p><%= alert %></p>
  <div class="container">
    <%= yield %>
		
	
<%= render 'layouts/footer'%>
</div>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>	
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


 </body>
</html>